### ISSUE TITLE
推荐改用jQuery的Ajax

### ISSUE THREAD

**Issue by SmallOyster** [ddawx123/DCP_SSOInterceptor#1]
如题，真心推荐改用jQuery的Ajax。

更简洁，更快，更好。

$.ajax({ });

**Comment by ddawx123** [comment]
之前是有考虑，但是为了和IE6兼容，不得不使用xmlhttp实现。。。jquery ajax的简单实现见
https://passport.dingstudio.cn/sso/static/js/oauth-ajax.js

**Comment by SmallOyster** [comment]
我会用……我很多地方都用了

只不过我只是建议你用而已 :joy:

其实现在很多都用jQuery的Ajax了……

**Comment by ddawx123** [comment]
嗯:blush: 主要是有些鬼地方的系统是XP，而且还不升级IE8。。。害得我没法登录网站:joy:

**Comment by SmallOyster** [comment]
……可怕……没几个人用XP了……

**Comment by ddawx123** [comment]
不不不，我祖父母家就是 还有某些宾馆。。。忒落伍，没办法。。有时候只能远程桌面连接到家里电脑:confused:

**Comment by SmallOyster** [comment]
好咯……那我没办法咯……

只不过我还是会继续用jQuery的 :joy::joy:
